#!/bin/sh

set -e


case "$1" in
    configure)
        virtualbox_version=@VIRTUALBOX_VERSION@
        ext_pack_file=$(mktemp -p /tmp Oracle_VM_VirtualBox_Extension_Pack-${virtualbox_version}.XXXXXXXXXX.vbox-extpack)
        wget -O ${ext_pack_file} "http://download.virtualbox.org/virtualbox/${virtualbox_version}/Oracle_VM_VirtualBox_Extension_Pack-${virtualbox_version}.vbox-extpack"
        VBoxManage extpack install --replace ${ext_pack_file}
        rm ${ext_pack_file}
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
